# Pandas Review Challenge

To review some basic concepts, attempt to perform these basic Pandas tasks on your own and then watch the walkthrough video to check your solutions.

Once your assignment is complete and you have watched the solution video to check your answers, make sure that you save it as `pandas_review` and upload it to CodeGrade to get credit for your work.

Import `numpy as np`, `pandas as pd`, and check your pandas version.

In [1]:
import numpy as np 
import pandas as pd
print(pd.__version__) # your version may be different

# set display columns - Do not change or CodeGrade may not function correctly
pd.set_option('display.max_columns', None)

2.2.2

## Series

**Q1:** Create a Pandas Series object called `Q1` from the following `arr` array.

In [3]:
arr = np.array([4,8,-3,1])

Q1 = pd.Series(arr)
Q1

0    4
1    8
2   -3
3    1
dtype: int32

**Q2:** Create a Pandas Series object called `Q2` from the above `arr` array with an index of `a`, `b`, `c`, `d`.

In [5]:
#Q2
Q2 = pd.Series(arr, index=['a','b','c','d'])
Q2

a    4
b    8
c   -3
d    1
dtype: int32

**Q3:** Index the `c` instance for the `Q2` Series and save it as `Q3`.

In [7]:
#Q3
Q3 = Q2['c']
Q3

-3

**Q4:**  Make a copy of the `Q2` Series and call it `Q4`. Change the `c` instance in `Q4` to `0`.

In [9]:
#Q4
Q4 = Q2.copy()

Q4['c'] = 0
Q4

a    4
b    8
c    0
d    1
dtype: int32

**Q5:** Filter all instances in `Q4` that are greater than `2` and save this as `Q5`.

In [13]:
#Q5
Q5 = Q4[Q4 > 2]
Q5

a    4
b    8
dtype: int32

**Q6:** Using a Python dictionary, create the following as a Series called `Q6` using the state as the index.
```
 Wyoming      581000
 Vermont      623000
 DC           714000
 Alaska       724000
 North Dakota 770000
```

In [17]:
#Q6
states = {'Wyoming': 581000,'Vermont': 623000,'DC': 714000,
          'Alaska': 724000,'North Dakota': 770000}

Q6 = pd.Series(states)
Q6

Wyoming         581000
Vermont         623000
DC              714000
Alaska          724000
North Dakota    770000
dtype: int64

# DataFrame

**Q7:** Using the below Python dictionary, create a DataFrame called `Q7`.

In [19]:
#Q7
data = {'book':['The Way of Kings','A Game of Thrones','The Hobbit',
                "Harry Potter and the Sorcerer's Stone",'The Lion, the Witch, and the Wardrobe'],
        'year_published': [2010,1996,1937,1997,1950],
        'amazon_rating': [5,4.5,5,5,5]}

Q7 = pd.DataFrame(data)
Q7

                                    book  year_published  amazon_rating
0                       The Way of Kings            2010            5.0
1                      A Game of Thrones            1996            4.5
2                             The Hobbit            1937            5.0
3  Harry Potter and the Sorcerer's Stone            1997            5.0
4  The Lion, the Witch, and the Wardrobe            1950            5.0

**Q8:** Make a copy of the `Q7` DataFrame and call it `Q8`.  Add a fourth column called `copies_owned` and assign an integer value of `1` to every row.

In [21]:
#Q8
Q8 = Q7.copy()

Q8['copies_owned'] = 1
Q8

,book,year_published,amazon_rating,copies_owned
0,The Way of Kings,2010,5.0,1
1,A Game of Thrones,1996,4.5,1
2,The Hobbit,1937,5.0,1
3,Harry Potter and the Sorcerer's Stone,1997,5.0,1
4,"The Lion, the Witch, and the Wardrobe",1950,5.0,1

**Q9:** Make a copy of `Q8` and call it `Q9`. Remove the fourth column called `copies_owned` from the `Q9` DataFrame.

In [23]:
#Q9
Q9 = Q8.copy()

Q9 = Q9.drop(['copies_owned'], axis=1)
Q9

                                    book  year_published  amazon_rating
0                       The Way of Kings            2010            5.0
1                      A Game of Thrones            1996            4.5
2                             The Hobbit            1937            5.0
3  Harry Potter and the Sorcerer's Stone            1997            5.0
4  The Lion, the Witch, and the Wardrobe            1950            5.0

**Q10:** Create a DataFrame called `Q10` using the below nested dictionary of dictionaries. (Note: outer keys are interpreted as columns, inner keys as row indices)

In [25]:
#Q10
pop = {'Nevada':{2001: 2.4, 2002: 2.9},
       'Ohio': {2000:1.5, 2001: 1.7, 2002: 3.6}}

Q10 = pd.DataFrame(pop)
Q10

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

**Q11:** Swap the columns and rows of `Q10` by using the transpose method `.T` and save this as `Q11`.

In [27]:
#Q11
Q11 = Q10.T
Q11

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

**Q12:** Change the columns in the `Q11` DataFrame to be in year order (earlier to later) and save this as `Q12`.

In [29]:
#Q12
Q12 = Q11.reindex(columns=[2000,2001,2002])
Q12

        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

**Q13:** Index only `Nevada` in the `Q12` DataFrame and save this as `Q13`.

In [31]:
#Q13
Q13 = Q12.loc['Nevada']
Q13

2000    NaN
2001    2.4
2002    2.9
Name: Nevada, dtype: float64

**Q14:** Select the `2001` column from the `Q12` DataFrame and save this as `Q14`.

In [33]:
#Q14
Q14 = Q12[2001]
Q14

Nevada    2.4
Ohio      1.7
Name: 2001, dtype: float64

**Q15:**  Select the `Ohio` row and the `2001` and `2002` columns from `Q12` and save this as `Q15`.

In [35]:
#Q15
Q15 = Q12.loc['Ohio',[2001,2002]]
Q15

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

**Q16:** Run the code below to create a DataFrame called `employees`. Filter only the employees that make above $90,000 and save this as `Q16`.

In [75]:
#Q16
table =  {'name': ['John', 'Jane', 'Billy', 'Tracy'],
         'age': [25, 27, 42, 31],
          'gender': ['M','F','M','F'],
         'profession': ['Developer', 'Analyst', 'Admin', 'Data Scientist'],
         'salary':[100000, 80000, 75000, 110000]
         }

employees = pd.DataFrame(table)
employees

    name  age gender      profession  salary
0   John   25      M       Developer  100000
1   Jane   27      F         Analyst   80000
2  Billy   42      M           Admin   75000
3  Tracy   31      F  Data Scientist  110000

In [87]:
employees['salary'] > 90000

0     True
1    False
2    False
3     True
Name: salary, dtype: bool

In [85]:
#Q16
Q16 = employees[employees['salary'] > 90000]
Q16

    name  age gender      profession  salary
0   John   25      M       Developer  100000
3  Tracy   31      F  Data Scientist  110000

**Q17:** Select only the names of the employees that make under $90,000 and save this as `Q17`.  Note: This should end up as a Series for CodeGrade to mark it correctly.

In [45]:
#Q17
Q17 = employees[employees['salary'] < 90000]['name']
Q17

1     Jane
2    Billy
Name: name, dtype: object

**Q18:** Select only the names of the employees that make under $90,000 and are over 30 years old.  Save this as `Q18`.

In [47]:
#Q18
Q18 = employees[(employees['salary'] < 90000) & (employees['age'] > 30)]['name']
Q18

2    Billy
Name: name, dtype: object

**Q19:** Our company has grown, and we have hired three new employees. Create a new DataFrame called `Q19` that adds these employees (`new_hires`) to the original DataFrame `employees`. Make sure that the index for the new DataFrame is labeled as `0` - `n-1`.

In [49]:
new_hires = {'name': ['Emily','Lukas','Janelle'],
            'age': [22, np.nan, 52],
             'gender': ['F','M','F'],
            'profession': ['Project Manager','ML Engineer','CIO'],
            'salary': [np.nan,135000,230000]}

Q19 = pd.concat([employees, pd.DataFrame(new_hires)], ignore_index=True)
Q19

      name   age gender       profession    salary
0     John  25.0      M        Developer  100000.0
1     Jane  27.0      F          Analyst   80000.0
2    Billy  42.0      M            Admin   75000.0
3    Tracy  31.0      F   Data Scientist  110000.0
4    Emily  22.0      F  Project Manager       NaN
5    Lukas   NaN      M      ML Engineer  135000.0
6  Janelle  52.0      F              CIO  230000.0

**Q20:** Make a copy of the `Q19` DataFrame and save it as `Q20`.  Add a new column called `departments` to the `Q20` DataFrame using the list below.

In [51]:
departments = ['IT','IT','Administration','IT','Communications','IT','Executive']

Q20 = Q19.copy()

Q20['departments'] = departments
Q20

      name   age gender       profession    salary     departments
0     John  25.0      M        Developer  100000.0              IT
1     Jane  27.0      F          Analyst   80000.0              IT
2    Billy  42.0      M            Admin   75000.0  Administration
3    Tracy  31.0      F   Data Scientist  110000.0              IT
4    Emily  22.0      F  Project Manager       NaN  Communications
5    Lukas   NaN      M      ML Engineer  135000.0              IT
6  Janelle  52.0      F              CIO  230000.0       Executive

**Q21:** Make a copy of the `Q20` DataFrame and save it as `Q21`.  You heard back from HR that Emily's salary should equal the employee with the lowest salary. Fill this missing value in `Q21` with the minimum salary (use `fillna()` and `min()` instead of hard coding the salary).

In [53]:
#Q21
Q21 = Q20.copy()

Q21['salary'] = Q21['salary'].fillna((Q21['salary'].min()))
Q21

      name   age gender       profession    salary     departments
0     John  25.0      M        Developer  100000.0              IT
1     Jane  27.0      F          Analyst   80000.0              IT
2    Billy  42.0      M            Admin   75000.0  Administration
3    Tracy  31.0      F   Data Scientist  110000.0              IT
4    Emily  22.0      F  Project Manager   75000.0  Communications
5    Lukas   NaN      M      ML Engineer  135000.0              IT
6  Janelle  52.0      F              CIO  230000.0       Executive

**Q22:** Make a copy of `Q21` and save it as `Q22`.  Add Lukas' age of `54` to the `Q22` DataFrame.

In [63]:
#make a copy
Q22 = Q21.copy()

#SettingWithCopyWarning
Q22.loc[Q22['name'] == 'Lukas','age'] = 54
Q22

      name   age gender       profession    salary     departments
0     John  25.0      M        Developer  100000.0              IT
1     Jane  27.0      F          Analyst   80000.0              IT
2    Billy  42.0      M            Admin   75000.0  Administration
3    Tracy  31.0      F   Data Scientist  110000.0              IT
4    Emily  22.0      F  Project Manager   75000.0  Communications
5    Lukas  54.0      M      ML Engineer  135000.0              IT
6  Janelle  52.0      F              CIO  230000.0       Executive

**Q23:** Sort the `Q22` DataFrame by the `age` column from youngest to oldest employee and save this as `Q23`.

In [65]:
#Q23
Q23 = Q22.sort_values(by='age')
Q23

      name   age gender       profession    salary     departments
4    Emily  22.0      F  Project Manager   75000.0  Communications
0     John  25.0      M        Developer  100000.0              IT
1     Jane  27.0      F          Analyst   80000.0              IT
3    Tracy  31.0      F   Data Scientist  110000.0              IT
2    Billy  42.0      M            Admin   75000.0  Administration
6  Janelle  52.0      F              CIO  230000.0       Executive
5    Lukas  54.0      M      ML Engineer  135000.0              IT

**Q24:** Using `value_counts()`, how many employees in the `Q23` DataFrame does each department have?  Save this as `Q24`.

In [67]:
#Q24
Q24 = Q23['departments'].value_counts()
Q24

departments
IT                4
Communications    1
Administration    1
Executive         1
Name: count, dtype: int64

**Q25:** Make a copy of the `Q23` DataFrame and save it as `Q25`.  Rename the `name` column in `Q25` to `employee_name`.

In [71]:
#Q25
Q25 = Q23.copy()
Q25 = Q25.rename(columns={'name':'employee_name'})
Q25

  employee_name   age gender       profession    salary     departments
4         Emily  22.0      F  Project Manager   75000.0  Communications
0          John  25.0      M        Developer  100000.0              IT
1          Jane  27.0      F          Analyst   80000.0              IT
3         Tracy  31.0      F   Data Scientist  110000.0              IT
2         Billy  42.0      M            Admin   75000.0  Administration
6       Janelle  52.0      F              CIO  230000.0       Executive
5         Lukas  54.0      M      ML Engineer  135000.0              IT

Good work!